# Generated by Django 6.0.7 on 2026-07-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateResearcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chercheur associé',
                'verbose_name_plural': 'Chercheurs associés',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('start_year', models.CharField(help_text='Ex : 2023 ou 2025-2026', max_length=9)),
                ('partner_university', models.CharField(max_length=255)),
                ('thesis_director', models.CharField(max_length=255)),
                ('co_supervisor', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Doctorant',
                'verbose_name_plural': 'Doctorants',
                'ordering': ['order', 'start_year', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Laboratoire d'Analyse, de Modélisation et d'Optimisation", max_length=255)),
                ('acronym', models.CharField(default='LAMO', max_length=20)),
                ('affiliation', models.CharField(default='Centre de Recherche en Mathématiques et Numérique (CRMN), Université de Djibouti', max_length=500)),
                ('mission', models.TextField(help_text='Paragraphe de mission (première section de la présentation).')),
                ('presentation_extra', models.TextField(blank=True, help_text='Paragraphes complémentaires de présentation, séparés par une ligne vide.')),
                ('teams_intro', models.TextField(blank=True, help_text="Texte d'introduction affiché au-dessus des équipes de recherche.")),
                ('address', models.CharField(blank=True, max_length=500)),
                ('director_name', models.CharField(blank=True, max_length=255)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('university_logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
            ],
            options={
                'verbose_name': 'Profil du laboratoire',
                'verbose_name_plural': 'Profil du laboratoire',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('category', models.CharField(choices=[('academic', 'Partenaire académique'), ('institutional', 'Partenaire institutionnel & socio-économique')], default='academic', max_length=20)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Équipe de recherche',
                'verbose_name_plural': 'Équipes de recherche',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermanentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='Grade / spécialité', max_length=255)),
                ('is_director', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='lab.researchteam')),
            ],
            options={
                'verbose_name': 'Membre permanent',
                'verbose_name_plural': 'Membres permanents',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='lab.researchteam')),
            ],
            options={
                'verbose_name': 'Thématique de recherche',
                'verbose_name_plural': 'Thématiques de recherche',
                'ordering': ['order', 'title'],
            },
        ),
    ]
