# Generated by Django 6.0.7 on 2026-07-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateresearcher',
            name='bio',
            field=models.TextField(blank=True, help_text='Présentation courte affichée sur la fiche du chercheur.'),
        ),
        migrations.AddField(
            model_name='associateresearcher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='bio',
            field=models.TextField(blank=True, help_text='Sujet de thèse ou présentation courte.'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='bio',
            field=models.TextField(blank=True, help_text='Présentation courte affichée sur la fiche du membre.'),
        ),
    ]
