# Generated by Django 6.0.7 on 2026-07-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_associateresearcher_bio_associateresearcher_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('conference', 'Conférence'), ('seminaire', 'Séminaire'), ('olympiades', 'Olympiades'), ('offre', 'Offre de thèse et de stage')], max_length=20)),
                ('title', models.CharField(help_text='Ex : 2e édition — M2ISDA 2027', max_length=255)),
                ('edition_label', models.CharField(blank=True, help_text='Ex : 1ère édition, Édition 2025', max_length=100)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('link', models.URLField(blank=True, help_text='Lien externe (inscription, appel à candidature...)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['category', 'order', 'year'],
            },
        ),
        migrations.AddField(
            model_name='labprofile',
            name='teams_conclusion',
            field=models.TextField(blank=True, help_text='Paragraphe sur la complémentarité des équipes, affiché en bas de la page Équipes.'),
        ),
    ]
