# Generated by Django 6.0.7 on 2026-07-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_activity_labprofile_teams_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentmember',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='phone',
            field=models.CharField(blank=True, help_text='Un ou plusieurs numéros, séparés par « | ».', max_length=120),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='role_tag',
            field=models.CharField(blank=True, help_text="Fonction complémentaire affichée en badge, ex : Doyen de l'IUT-T", max_length=120),
        ),
    ]
