# Generated by Django 6.0.7 on 2026-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_permanentmember_email_secondary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('garant', models.CharField(blank=True, help_text="Garant de l'HDR", max_length=255)),
                ('institutions', models.CharField(blank=True, max_length=500)),
                ('specialization', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habilitation à Diriger des Recherches',
                'verbose_name_plural': 'Habilitations à Diriger des Recherches',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Revue, volume, pages, année. Ex : Scientific African, 31 (2026): e03262.', max_length=300)),
                ('is_forthcoming', models.BooleanField(default=False, help_text="Coché si l'article est « à paraître ».")),
                ('link', models.URLField(blank=True, help_text="Lien DOI, HAL ou arXiv de l'article.")),
                ('link_label', models.CharField(blank=True, default='DOI', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('funder', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Projet réalisé'), ('ongoing', 'Projet en cours')], default='ongoing', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_publications', models.ManyToManyField(blank=True, related_name='projects', to='lab.publication')),
            ],
            options={
                'verbose_name': 'Projet de recherche',
                'verbose_name_plural': 'Projets de recherche',
                'ordering': ['status', 'order'],
            },
        ),
    ]
