# Generated by Django 6.0.7 on 2026-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_habilitation_publication_researchproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(help_text='Ex : Master 1 IAMD', max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cours de Master',
                'verbose_name_plural': 'Cours de Master',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='people',
            field=models.CharField(blank=True, help_text='Présentateur, intervenant ou représentation du LAMO, ex : Dr Yahyeh SOULEIMAN', max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('conference', 'Conférence'), ('seminaire', 'Séminaire'), ('olympiades', 'Olympiades'), ('offre', 'Offre de thèse et de stage'), ('participation', 'Participation à une manifestation scientifique'), ('editorial', 'Responsabilité éditoriale'), ('jury', 'Participation à un jury de thèse'), ('stage', 'Encadrement de stage'), ('capacity', 'Renforcement de capacités')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='year',
            field=models.CharField(blank=True, help_text="Date ou période de l'activité.", max_length=20),
        ),
    ]
