# Generated by Django 6.0.7 on 2026-07-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_mastercourse_activity_location_activity_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='lab.activity')),
            ],
            options={
                'verbose_name': "Photo supplémentaire d'activité",
                'verbose_name_plural': "Photos supplémentaires d'activité",
                'ordering': ['order'],
            },
        ),
    ]
