# Generated by Django 6.0.7 on 2026-07-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_activityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['category', '-sort_date', '-order'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='doctorant',
            options={'ordering': ['-start_year', 'order', 'full_name'], 'verbose_name': 'Doctorant', 'verbose_name_plural': 'Doctorants'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'order'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='researchproject',
            options={'ordering': ['-order'], 'verbose_name': 'Projet de recherche', 'verbose_name_plural': 'Projets de recherche'},
        ),
        migrations.AddField(
            model_name='activity',
            name='sort_date',
            field=models.DateField(blank=True, help_text="Date utilisée uniquement pour classer l'activité de la plus récente à la plus ancienne.", null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Année de publication, utilisée pour classer les articles du plus récent au plus ancien.', null=True),
        ),
    ]
