# Generated by Django 6.0.7 on 2026-07-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_activity_options_alter_doctorant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['category', '-sort_date', 'order'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
    ]
