# Generated by Django 6.0.7 on 2026-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitation',
            name='title',
            field=models.CharField(blank=True, help_text="Titre des travaux de l'HDR.", max_length=500),
        ),
    ]
