# Generated by Django 6.0.7 on 2026-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_habilitation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.FileField(blank=True, help_text='Document à télécharger (livret, programme...).', null=True, upload_to='activities/documents/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='document_label',
            field=models.CharField(blank=True, default='Télécharger le livret', help_text='Texte du bouton de téléchargement.', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_fit_contain',
            field=models.BooleanField(default=False, help_text='Cocher pour les visuels/affiches qui doivent rester entièrement visibles sans recadrage.'),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='thesis_link',
            field=models.URLField(blank=True, help_text='Lien vers la thèse de doctorat du membre.'),
        ),
    ]
