# Generated by Django 6.0.7 on 2026-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_activity_document_activity_document_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text="Affiche ou visuel associé à l'actualité.", null=True, upload_to='news/'),
        ),
    ]
