# Generated by Django 6.0.7 on 2026-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labprofile',
            name='affiliation',
            field=models.CharField(default='Laboratoire de Recherche en Mathématiques et Numérique (LRMN), Université de Djibouti', max_length=500),
        ),
    ]
