# Generated by Django 6.0.7 on 2026-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_alter_labprofile_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse électronique universitaire du doctorant.', max_length=254),
        ),
    ]
