# Generated by Django 6.0.7 on 2026-07-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_doctorant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentmember',
            name='scholar_link',
            field=models.URLField(blank=True, help_text='Lien vers le profil Google Scholar / liste des articles du membre.'),
        ),
    ]
