# Generated by Django 6.0.7 on 2026-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_permanentmember_scholar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.FileField(blank=True, help_text='Vidéo à regarder directement sur la page (mp4).', null=True, upload_to='activities/videos/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='video_label',
            field=models.CharField(blank=True, default='Vidéo', help_text='Légende affichée au-dessus du lecteur vidéo.', max_length=100),
        ),
    ]
