# Generated by Django 6.0.7 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_activity_video_activity_video_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document_pending',
            field=models.BooleanField(default=False, help_text="Affiche « Document bientôt disponible » tant qu'aucun fichier n'est attaché."),
        ),
    ]
