# Generated by Django 6.0.7 on 2026-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_activity_document_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labprofile',
            name='affiliation',
            field=models.CharField(default='Centre de Recherche en Mathématiques et Numérique (CRMN), Université de Djibouti', max_length=500),
        ),
    ]
