# Generated by Django 6.0.7 on 2026-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_alter_labprofile_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateresearcher',
            name='scholar_link',
            field=models.URLField(blank=True, help_text='Lien vers le profil Google Scholar / liste des articles du chercheur.'),
        ),
    ]
