# Generated by Django 6.0.7 on 2026-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_associateresearcher_scholar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='document',
            field=models.FileField(blank=True, help_text='Document à télécharger (programme, livret...).', null=True, upload_to='news/documents/'),
        ),
        migrations.AddField(
            model_name='news',
            name='document_label',
            field=models.CharField(blank=True, default='Télécharger le programme', help_text='Texte du bouton de téléchargement.', max_length=100),
        ),
    ]
