"""
Django settings for lamo_site project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# En production (Render), SECRET_KEY est fournie via une variable d'environnement.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-m_)_t3ez$lj8fz*yw!#zhlg8xw*izddrl9@m25tr*2vsngu=sv'
)

# DEBUG=False par défaut dès qu'on tourne sur Render ; True en local par défaut.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
if DEBUG:
    ALLOWED_HOSTS += ['127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ('127.0.0.1', 'localhost')]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lamo_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'lab.context_processors.lab_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'lamo_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Utilise DATABASE_URL si fourni (ex: Postgres sur Render), sinon SQLite en local.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Djibouti'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Administration (django-unfold) — habillage aux couleurs du LAMO
# https://unfoldadmin.com/docs/configuration/settings/

UNFOLD = {
    'SITE_TITLE': 'Espace de gestion LAMO',
    'SITE_HEADER': 'LAMO',
    'SITE_SUBHEADER': 'Espace de gestion',
    'SITE_SYMBOL': 'functions',
    'SITE_LOGO': lambda request: static('lab/img/logo_lamo.png'),
    'SITE_ICON': lambda request: static('lab/img/logo_lamo.png'),
    'SITE_FAVICONS': [
        {'rel': 'icon', 'type': 'image/png', 'href': lambda request: static('lab/img/logo_lamo.png')},
    ],
    'SITE_DROPDOWN': [
        {
            'icon': 'open_in_new',
            'title': _('Voir le site LAMO'),
            'link': reverse_lazy('lab:home'),
        },
    ],
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'BORDER_RADIUS': '10px',
    'STYLES': [
        lambda request: static('lab/css/admin.css'),
    ],
    'SCRIPTS': [
        lambda request: static('lab/js/admin.js'),
    ],
    'COLORS': {
        'primary': {
            '50': 'oklch(97.0% 0.018 255.3)',
            '100': 'oklch(93.0% 0.035 255.3)',
            '200': 'oklch(86.0% 0.062 255.3)',
            '300': 'oklch(77.0% 0.092 255.3)',
            '400': 'oklch(68.0% 0.118 255.3)',
            '500': 'oklch(58.0% 0.136 255.3)',
            '600': 'oklch(50.2% 0.145 255.3)',
            '700': 'oklch(42.0% 0.128 255.3)',
            '800': 'oklch(34.0% 0.108 255.3)',
            '900': 'oklch(27.0% 0.082 255.3)',
            '950': 'oklch(19.0% 0.052 255.3)',
        },
    },
    'LOGIN': {
        'image': lambda request: static('lab/img/affiche_lamo.jpg'),
    },
    'DASHBOARD_CALLBACK': 'lab.admin.dashboard_callback',
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': _('Aperçu'),
                'separator': False,
                'items': [
                    {
                        'title': _('Tableau de bord'),
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                ],
            },
            {
                'title': _('Laboratoire'),
                'separator': True,
                'collapsible': False,
                'items': [
                    {
                        'title': _('Profil du laboratoire'),
                        'icon': 'account_balance',
                        'link': reverse_lazy('admin:lab_labprofile_changelist'),
                    },
                    {
                        'title': _('Équipes de recherche'),
                        'icon': 'diversity_3',
                        'link': reverse_lazy('admin:lab_researchteam_changelist'),
                    },
                    {
                        'title': _('Axes de recherche'),
                        'icon': 'hub',
                        'link': reverse_lazy('admin:lab_researchtheme_changelist'),
                    },
                ],
            },
            {
                'title': _('Membres'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Membres permanents'),
                        'icon': 'school',
                        'link': reverse_lazy('admin:lab_permanentmember_changelist'),
                    },
                    {
                        'title': _('Doctorants'),
                        'icon': 'cast_for_education',
                        'link': reverse_lazy('admin:lab_doctorant_changelist'),
                    },
                    {
                        'title': _('Chercheurs associés'),
                        'icon': 'public',
                        'link': reverse_lazy('admin:lab_associateresearcher_changelist'),
                    },
                ],
            },
            {
                'title': _('Vie scientifique'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Activités'),
                        'icon': 'event',
                        'link': reverse_lazy('admin:lab_activity_changelist'),
                    },
                    {
                        'title': _('Actualités'),
                        'icon': 'campaign',
                        'link': reverse_lazy('admin:lab_news_changelist'),
                    },
                ],
            },
            {
                'title': _('Production scientifique'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Publications'),
                        'icon': 'article',
                        'link': reverse_lazy('admin:lab_publication_changelist'),
                    },
                    {
                        'title': _('Projets de recherche'),
                        'icon': 'science',
                        'link': reverse_lazy('admin:lab_researchproject_changelist'),
                    },
                    {
                        'title': _('HDR'),
                        'icon': 'workspace_premium',
                        'link': reverse_lazy('admin:lab_habilitation_changelist'),
                    },
                ],
            },
            {
                'title': _('Formations & partenaires'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Enseignements de Master'),
                        'icon': 'menu_book',
                        'link': reverse_lazy('admin:lab_mastercourse_changelist'),
                    },
                    {
                        'title': _('Partenaires'),
                        'icon': 'handshake',
                        'link': reverse_lazy('admin:lab_partner_changelist'),
                    },
                ],
            },
            {
                'title': _('Accès & sécurité'),
                'separator': True,
                'collapsible': True,
                'items': [
                    {
                        'title': _('Comptes utilisateurs'),
                        'icon': 'manage_accounts',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                    {
                        'title': _('Groupes'),
                        'icon': 'groups',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
        ],
    },
}
